### ISSUE TITLE
What should I provide as the team_context ? def get_backlogs(self, team_context):

### ISSUE THREAD

**Issue by MartinCalderon** [Microsoft/vsts-python-api#103]
Hello,

Would be possible to help?. I'm trying to understand where Team Context comes from. For example the function in the vsts-python-api/vsts/vsts/work/v4_1/work_client.py

What should I provide as the team_context ?

def get_backlogs(self, team_context):
"""GetBacklogs.
[Preview API] List all backlog levels
:param :class:<TeamContext> <work.v4_1.models.TeamContext> team_context: The team context for the operation
:rtype: [BacklogLevelConfiguration]
"""
Thank you in advance, this is a very nice SDK. @tedchamb , @vbossica

**Comment by tedchamb** [comment]
The team_context specifies which team to get the backlog for.  If you want to get the backlog for the default team for the project, you can specify one of the project properties with the name or id of the project, and leave the team fields as None.  If you want the backlog for a specific team in your project then you will need to specify both a project in one of the project properties and the team in one of the team properties.   The team_context model has redundant properties as a fallout from the code generation tool.  The source of the model is C# where the `_id` fields expect GUIDs.  The fields without `_id` are strings in c#.   In python they are both strings, so the model does not translate well.  The important thing when using the python sdk is that one of the project properties should always be set in a team context, and one of the team properties may or may not be set depending on whether you want the default team or a specific team.  

`    :param project: The team project Id or name.  Ignored if ProjectId is set.`
`    :param project_id: The Team Project ID.  Required if Project is not set.`
`    :param team: The Team Id or name.  Ignored if TeamId is set.`
`    :param team_id: The Team Id`

Required:  Set either project or project_id
Optional: Set either team or team_id
