### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by LinuxChristian** [Microsoft/vsts-python-api#30]
Hi,

I have tried to use the library but cannot see how. If I do `import vsts` the module does not seem to contain any methods I can call.
Could you add a small snippet to the readme? Just to get people started. Right now I am writing my own code to communicate with VSTS over RESTful, but would really like to use this library insted.

Thanks

**Comment by vbossica** [comment]
Here is how you would list the projects of a particular instance:

```
from vsts.vss_connection import VssConnection
from msrest.authentication import BasicAuthentication

token='REDACTED'
team_instance='https://REDACTED.visualstudio.com'

credentials = BasicAuthentication('', token)
connection = VssConnection(base_url=team_instance, creds=credentials)
core_client = connection.get_client('vsts.core.v4_0.core_client.CoreClient')

team_projects = core_client.get_projects()

for project in team_projects:
    print(project.name)
```

But, if you can, using the Python VSTS CLI client (https://github.com/Microsoft/vsts-cli) is a lot simpler.

**Comment by LinuxChristian** [comment]
Thanks a lot for the answer. I will try it out.
