### ISSUE TITLE
Class WorkItemExpand is missing

### ISSUE THREAD

**Issue by vbossica** [Microsoft/vsts-python-api#31]
Class `WorkItemExpand`, referenced in `WorkItemTrackingClient` is missing from the code base.

But using a `str` instead of a `WorkItemExpand` instance works. So either the generated code doesn't contain all the classes, or the generated documentation is misleading.

**Comment by tedchamb** [comment]
Same code generation issue as #28

**Comment by tedchamb** [comment]
Thanks for reporting this.  This ended up being a different issue.   #34 has the fix.
