### ISSUE TITLE
Documentation is non-existent 

### ISSUE THREAD

**Issue by dalemyers** [Microsoft/vsts-python-api#35]
I attempted to use this for more than a non-trivial case, and it turned out to be extremely difficult due to the lack of documentation. It's possible, but difficult. There are API calls which fail for no apparent reason, and without documentation, I'm left debugging the library code to figure out what went wrong.

**Comment by tedchamb** [comment]
The python SDK is a thin wrapper around the VSTS REST APIs.  Our REST api documentation should be very helpful while working with this python SDK.

https://docs.microsoft.com/en-us/rest/api/vsts/

A good place to see real examples of how to use this SDK, is our vsts-cli repo:
https://github.com/Microsoft/vsts-cli

In the vsts-cli repo, you will find files like this one.  It contains examples for working with pull requests:
https://github.com/Microsoft/vsts-cli/blob/dev/src/common_modules/vsts-cli-code-common/vsts/cli/code/common/pull_request.py

**Comment by tedchamb** [comment]
@dalemyers Can you provide details on the "API calls which fail for no apparent reason"?  The service should return actionable error messages.   This is not always the case, so when we find instances, we want to file bugs against the service team, to ensure they address the issue.  Helpful details would include which api was called, what arguments were used (scrubbing any private data) and the response message returned from the server.

**Comment by dalemyers** [comment]
I don't have the code any more as I abandoned it and wrote my own wrapper. However, I was most likely attempting to comment on a PR.

**Comment by tedchamb** [comment]
Thanks @dalemyers , if you decide to give it another try, please do send us the details, so we can fix the non-actionable errors you ran into.

**Comment by tedchamb** [comment]
Added link to REST API documentation to readme.
commit 7199c5f98dca763a6bdd1124b67801aef6a446fd
