### ISSUE TITLE
Documentation for adding a task (and subtasks) to VSTS

### ISSUE THREAD

**Issue by aagostini-tada** [Microsoft/vsts-python-api#40]
Nice work on the new library! I've been able to install and run it successfully. Now I'm jsut scratching my head wondering how to actually add tasks in VSTS using this. Will you be adding documentation on this soon? Would I be able to get a hint (I tried searching through the source code but got lost with over 200 hits to the phrase 'task')?

**Comment by tedchamb** [comment]
This library is light weight python wrapper for our REST API, therefore you will should find the VSTS REST API documentation useful.  The distributed task area is available in the dev branch of this repo now, and I plan to merge it to master and publish next week.

VSTS REST API docs: https://docs.microsoft.com/en-us/rest/api/vsts/

I hope this helps,
Ted
