### ISSUE TITLE
ImportError: No module named vss_connection

### ISSUE THREAD

**Issue by Abdelkrim** [Microsoft/vsts-python-api#41]
**How to reproduce**

1. I have executed 'pip install vsts' - see [A]
2. I have written the code to display the projects list [B]
3. I execute 'python vsts.py' 

**I am not interested by any other solution such as "run vsts-cli" :-)**

**An ERROR is generated:** 

c:\VSTS>python vsts.py
Traceback (most recent call last):
  File "vsts.py", line 1, in <module>
    from vsts.vss_connection import VssConnection
  File "c:\VSTS\vsts.py", line 1, in <module>
    from vsts.vss_connection import VssConnection
ImportError: No module named vss_connection

**[B] list projects**

https://github.com/Microsoft/vsts-python-api

**[A] pip install vsts**

> c:\VSTS>pip install vsts
> Requirement already satisfied: vsts in c:\python27\lib\site-packages
> Requirement already satisfied: msrest>=0.4.5 in c:\python27\lib\site-packages (from vsts)
> Requirement already satisfied: isodate>=0.6.0 in c:\python27\lib\site-packages (from msrest>=0.4.5->vsts)
> Requirement already satisfied: requests-oauthlib>=0.5.0 in c:\python27\lib\site-packages (from msrest>=0.4.5->vsts)
> Requirement already satisfied: requests~=2.14 in c:\python27\lib\site-packages (from msrest>=0.4.5->vsts)
> Requirement already satisfied: certifi>=2017.4.17 in c:\python27\lib\site-packages (from msrest>=0.4.5->vsts)
> Requirement already satisfied: enum34>=1.0.4; python_version < "3.4" in c:\python27\lib\site-packages\enum34-1.0.4-py2.7
> .egg (from msrest>=0.4.5->vsts)
> Requirement already satisfied: six in c:\python27\lib\site-packages (from isodate>=0.6.0->msrest>=0.4.5->vsts)
> Requirement already satisfied: oauthlib>=0.6.2 in c:\python27\lib\site-packages (from requests-oauthlib>=0.5.0->msrest>=
> 0.4.5->vsts)
> Requirement already satisfied: idna<2.7,>=2.5 in c:\python27\lib\site-packages (from requests~=2.14->msrest>=0.4.5->vsts
> )
> Requirement already satisfied: urllib3<1.23,>=1.21.1 in c:\python27\lib\site-packages (from requests~=2.14->msrest>=0.4.
> 5->vsts)
> Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\python27\lib\site-packages (from requests~=2.14->msrest>=0.4.
> 5->vsts)
> 
>

**Comment by tedchamb** [comment]
try running: `python -m pip list`, which will list all packages installed for the instance of python that is in your path.  If vsts is not listed, you can run `python -m pip install vsts`, to install it for this instance of python.

**Comment by eltoncezar** [comment]
this is happening for me too. `python -m pip list` is returning as expected.
```
Package                       Version
----------------------------- ---------
vsts                          0.1.14
```

**Comment by tedchamb** [comment]
@eltoncezar, can you share sample code and stack trace of the error?

**Comment by eltoncezar** [comment]
Sure. Sample code is the same as provided in [Getting Started](https://github.com/Microsoft/vsts-python-api#getting-started). I only changed the `token` and `team_instance` variables.
I also tried to add the path `C:\Python27\Lib\site-packages\vsts` to the `PYTHONPATH` var.

Stack trace:
```
$ cd "c:\dev\python" ; env "PYTHONIOENCODING=UTF-8" "PYTHONUNBUFFERED=1" "C:\Python27\python.exe" "c:\Users\elton.cezar\.vscode\extensions\ms-python.python-2018
.7.1\pythonFiles\PythonTools\visualstudio_py_launcher.py" "c:\dev\python" 62926 34806ad9-833a-4524-8cd6-18ca4aa74f14 RedirectOutput,RedirectOutput "c:\dev\pytho
n\vsts.py"
Traceback (most recent call last):
  File "c:\dev\python\vsts.py", line 2, in <module>
    from vsts.vss_connection import VssConnection
  File "c:\dev\python\vsts.py", line 2, in <module>
    from vsts.vss_connection import VssConnection
ImportError: No module named vss_connection
```

My enviroment is:
Python 2.7 running through VSCode on Windows 10 x64

**Comment by eltoncezar** [comment]
Actually, I gave up. But thanks for your help!
