### ISSUE TITLE
Mismatch between TeamContext and query_by_wiql and query_by_wiql

### ISSUE THREAD

**Issue by rbnswartz** [Microsoft/vsts-python-api#42]
Both WorkItemTrackingClient.query_by_wiql() and WorkItemTrackingClient.query_by_wiql() take in TeamContext as a parameter but are accessing fields that don't exist on TeamContext but similar fields exist. For example instead of team_id which exists on the TeamContext it tries to use teamId. The same is true for project_id. I would submit a PR to fix it but the auto-generation warning at the top of the file scares me away.

**Comment by tedchamb** [comment]
Fixed with #43

**Comment by tedchamb** [comment]
@rbnswartz thanks for reporting this issue!  It is now fixed in the dev branch.
