### ISSUE TITLE
Pip install only contains <0.1.1 beta versions

### ISSUE THREAD

**Issue by kfishster** [Microsoft/vsts-python-api#44]
Hello, 

I've been using the  0.1.0b2 of the API, however, as 0.1.1 brings more advanced support for artifacts/file_container I was wondering if it were possible to publish the updated version to pip so that I can easily install it via pip automation.

Thanks!

**Comment by tedchamb** [comment]
0.1.1 is now available.
https://pypi.org/project/vsts/
`pip install vsts --upgrade`
