### ISSUE TITLE
how to get a team's iterations?

### ISSUE THREAD

**Issue by dreaminplus** [Microsoft/vsts-python-api#45]
Hi, here I want to get a team's iterations using vsts-python-api to make velocity-like chart? But I couldn't find the API... (I am using TFS) Maybe it has been existed.. I guess.

**Comment by tedchambers** [comment]
The python SDK is a thin wrapper around the REST API.  You can find information here on the REST API here:  https://docs.microsoft.com/en-us/rest/api/vsts/work/iterations/get

client: https://github.com/Microsoft/vsts-python-api/blob/dev/vsts/vsts/work/v4_1/work_client.py
method: get_team_iterations

This client is found in the dev branch and is not yet published on the python index, but it should be published this week.

**Comment by tedchamb** [comment]
0.1.1 is now available, and has the work client.
https://pypi.org/project/vsts/
pip install vsts --upgrade
