### ISSUE TITLE
GitClientBase.get_changes method returns error (v4.0)

### ISSUE THREAD

**Issue by WladdGorshenin** [Microsoft/vsts-python-api#47]
I get error “Unable to deserialize to object: type, AttributeError: type object 'ChangeCountDictionary' has no attribute '_validation'” while using get_changes method of a git client (version 4.0). Everything the rest works well.

**Comment by tedchamb** [comment]
I've reproed this issue, and will provide a fix soon.

**Comment by tedchamb** [comment]
#49 fixes this

**Comment by WladdGorshenin** [comment]
Hi @tedchamb, I tried the updated vsts module (0.1.1) today. GitClientBase.get_changes method doesn't raise any error now, but outputs a list with an empty changes. Could you please check it.

**Comment by tedchamb** [comment]
version 0.1.2 has been published with the fix.

**Comment by WladdGorshenin** [comment]
@tedchamb , it works! Thank you for the instance fix.
