### ISSUE TITLE
Work module not found

### ISSUE THREAD

**Issue by layoub29** [Microsoft/vsts-python-api#48]
Hello, I have a VssConnection and I have been able to get most clients from it except I am having trouble with the work client. I'm using the following code to get the client:
work_client = connection.get_client('vsts.work.v4_0.work_client.WorkClient')

And the error I'm getting is:
ModuleNotFoundError: No module named 'vsts.work'

Can you please tell me how to initialize a work client?

**Comment by tedchamb** [comment]
This is available in the dev branch, which has not been published on the python index yet.  I hope to publish it by end of week.  

As a workaround you can clone the repo, and install with the `pip install -e .` command.
