### ISSUE TITLE
Version 0.1.1 doesn't have a Git 4_1 client

### ISSUE THREAD

**Issue by vtbassmatt** [Microsoft/vsts-python-api#51]
0.1.0b1 had a git/v4_1/git_client.py module. When I upgraded to 0.1.1, that file no longer exists. v4_0 still has git_client.py, so I think this is a codegen bug.

**Comment by tedchamb** [comment]
@vtbassmatt Thanks for pointing this out.  I'll try and get a fix published today.

**Comment by tedchamb** [comment]
0.1.2 has been published with the fix.
