### ISSUE TITLE
Deserialization error on TaskAgentClient.get_agents(pool_id)

### ISSUE THREAD

**Issue by plang85** [Microsoft/vsts-python-api#65]
I'm getting 'msrest.exceptions.DeserializationError: Cannot deserialize as [number] an object of type <class 'str'>' when calling get_agents(some_pool_id) on TaskAgentClient (v4.0)

**Comment by tedchamb** [comment]
Thanks for reporting @plang85 .  #67 addresses this issue.

**Comment by tedchamb** [comment]
The fix is available in 0.1.6 on pypi
