### ISSUE TITLE
How to get a list of a work items

### ISSUE THREAD

**Issue by WladdGorshenin** [Microsoft/vsts-python-api#66]
What is the appropriate class and method to request a list of work items (specifically, bugs) for a project?

**Comment by tedchamb** [comment]
Use the following client for work item tracking:

<pre>
from vsts.vss_connection import VssConnection

connection = VssConnection(get_base_url(team_instance), creds=credentials)
client = connection.get_client('vsts.work_item_tracking.v4_1.work_item_tracking_client.WorkItemTrackingClient')
</pre>

See code here for examples of how our VSTS CLI, queries work items:
https://github.com/Microsoft/vsts-cli/blob/dev/src/common_modules/vsts-cli-work-common/vsts/cli/work/common/work_item.py
