### ISSUE TITLE
How approve a pending release? 

### ISSUE THREAD

**Issue by Alexlofern** [Microsoft/vsts-python-api#71]
Hi,

I'm trying making a simple approve with my code, but isn't working.

(...)
client.update_release_approval(approval='{  "status": "approved",  "comments": "Good to go!"}', project="projectX", approval_id=3321)

I believe that my approval is wrong, how I create than?

**Comment by tedchamb** [comment]
you need to use the release approval model:

Something like:
`approval=ReleaseApproval(status='approved', comments='Good to go!')`
