### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by zlogo** [Microsoft/vsts-python-api#72]
I am behind a proxy and so far have not been able to figure out how proxy details can be defined. Can you please give me an example of how to define proxy setting and proxy certificate?

**Comment by tedchamb** [comment]
You can specify the proxy by setting the environment variable `HTTPS_PROXY` or `HTTP_PROXY` to the url of your proxy.

If your proxy certificate is properly signed then there is nothing else you need to do.  If it is not you can follow instructions here:  Microsoft/vsts-cli/issues/76

**Comment by zlogo** [comment]
Thank you, this solved my problem.
