### ISSUE TITLE
Request to add Service Endpoint

### ISSUE THREAD

**Issue by brichins** [Microsoft/vsts-python-api#81]
I'd like to see the Service Endpoint REST API added to this library (https://docs.microsoft.com/en-us/rest/api/vsts/serviceendpoint/endpoints?view=vsts-rest-4.1).  It would help when programmatically creating endpoints.

Could you also explain how the APIs are generated?  I'm guessing they're autogenerated from OpenAPI/Swagger definitions.  I didn't find anything in the scripts directory that shows how to generate the code.  Any pointers there would be helpful.

Thanks,

Brandon Richins

**Comment by tedchamb** [comment]
@brichins The clients are generated using an internal tool available only in the product build system. It uses reflection on the binaries to find information on our controllers, models and routes.  We use this tool to generate c#, typescript, node.js, swagger 2.0, and python clients.  The documentation you found for the REST end points is then generated from the swagger 2.0.

**Comment by brichins** [comment]
Thanks for your response describing the process.  As far as adding the VSTS Service Endpoint REST API to the python-api, are you accepting that as a feature request?

**Comment by tedchamb** [comment]
@brichins Yes, see following pull request: #82

**Comment by tedchamb** [comment]
https://github.com/Microsoft/vsts-python-api/releases/tag/0.1.9
