### ISSUE TITLE
How to reproduce VSTS "History" tab with Python API?

### ISSUE THREAD

**Issue by WladdGorshenin** [Microsoft/vsts-python-api#86]
Hi @tedchamb , could you please help me once again. 

In my project I need to get a list of all modification for a particular file in a repo. It's similar to what "History" tab does in VSTS
![capture](https://user-images.githubusercontent.com/38522968/41902949-f70641ba-7934-11e8-911f-5aca82de26e7.PNG)

What is the best way to achieve it with Python API?

**Comment by tedchamb** [comment]
I believe you want to use this api:  
https://docs.microsoft.com/en-us/rest/api/vsts/git/commits/get%20commits?view=vsts-rest-4.1

Which correlates to the `get_commits` method on the `git_client`.  You can set the `item_path` in the `search_criteria` parameter.

**Comment by WladdGorshenin** [comment]
Hi @tedchamb , thank you for the reply. It's exactly what I need. I though of that method but was confused with item_path argument thinking it's related to a work item path.
