### ISSUE TITLE
Unable to use with Lambda - File System Dependency

### ISSUE THREAD

**Issue by jonshern** [Microsoft/vsts-python-api#90]
I am noticing that when i use this library and deploy to lambda i get the error 
Read-only file system: '/home/sbx_user1119'
It seems that this library uses the file system for caching

**Comment by tedchamb** [comment]
That is correct.  We cache data to the file system under the user directory by default.  You can override where the cached files get written to by setting the following environment variable: `VSTS_CACHE_DIR`.  I am not familiar with the details of the lambda deployment, is the entire file system read-only, or is there a directory you can write to?

https://github.com/Microsoft/vsts-python-api/blob/0d9537016bd45cf7f2140433c0ec54b44768f726/vsts/vsts/_file_cache.py#L111

**Comment by tedchamb** [comment]
@jonshern, I'm closing this issue, please reply back if you have any further questions regarding this issue, and I can reopen it.

**Comment by jonshern** [comment]
os.environ['VSTS_CACHE_DIR'] = '/tmp/'

Fixes it

**Comment by jithurjacob** [comment]
The variable has been renamed to 'AZURE_DEVOPS_CACHE_DIR'  so use

os.environ['AZURE_DEVOPS_CACHE_DIR'] = '/tmp/'

**Comment by ralcorta** [comment]
**Confirming workaround for AWS Lambda (Read-only file system)**

I encountered this same OSError: [Errno 30] Read-only file system issue while running the library in an AWS Lambda (Python 3.12) environment.

The library attempts to initialize the cache in the user's home directory.
In AWS Lambda, the default `HOME` directory is read-only, and only `/tmp` is writable.

I found that setting `XDG_CACHE_HOME` alone was not sufficient in my case.
To make the library work correctly, I had to explicitly override the `HOME` directory and point it to `/tmp`.

**Workarounds**
**_Option 1: Infrastructure Level (Terraform / Environment Variables)_**

This is the cleanest solution. Set the environment variables directly in your Lambda configuration:

```terraform
environment {
  variables = {
    HOME           = "/tmp"
    XDG_CACHE_HOME = "/tmp/.cache"
  }
}
```

**_Option 2: Python Code (Monkeypatch)_**

If modifying infrastructure is not possible, inject the environment variables before importing azure.devops:

```
import os

# AWS Lambda read-only FS fix: Override HOME to use /tmp
os.environ["HOME"] = "/tmp"
os.environ["XDG_CACHE_HOME"] = "/tmp/.cache"

from azure.devops.connection import Connection

```

Hope this helps others facing the same issue in serverless environments!
